// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXq1ChLbNpFz48dHgXMlkbyfaQ9qB5Ztc',
    appId: '1:852070449580:web:ec12dda325d72d76ea7a09',
    messagingSenderId: '852070449580',
    projectId: 'job-application-a8fde',
    authDomain: 'job-application-a8fde.firebaseapp.com',
    storageBucket: 'job-application-a8fde.appspot.com',
    measurementId: 'G-ZC6DL3CDLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpd5jKaceWIhL7dZlZBtOXbC8-9DHd76E',
    appId: '1:852070449580:android:44fbf83cff9659d2ea7a09',
    messagingSenderId: '852070449580',
    projectId: 'job-application-a8fde',
    storageBucket: 'job-application-a8fde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyQCy6c-EMwDL8fKHMMcp8uDXF-T2Bo9g',
    appId: '1:852070449580:ios:9ec857574525634fea7a09',
    messagingSenderId: '852070449580',
    projectId: 'job-application-a8fde',
    storageBucket: 'job-application-a8fde.appspot.com',
    iosBundleId: 'com.example.jobApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyQCy6c-EMwDL8fKHMMcp8uDXF-T2Bo9g',
    appId: '1:852070449580:ios:9ec857574525634fea7a09',
    messagingSenderId: '852070449580',
    projectId: 'job-application-a8fde',
    storageBucket: 'job-application-a8fde.appspot.com',
    iosBundleId: 'com.example.jobApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXq1ChLbNpFz48dHgXMlkbyfaQ9qB5Ztc',
    appId: '1:852070449580:web:0108da96c77a20a2ea7a09',
    messagingSenderId: '852070449580',
    projectId: 'job-application-a8fde',
    authDomain: 'job-application-a8fde.firebaseapp.com',
    storageBucket: 'job-application-a8fde.appspot.com',
    measurementId: 'G-8PMWLHMJBL',
  );
}
